# Generated by Django 4.0.5 on 2022-06-27 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('name', models.CharField(db_column='tx_name', max_length=128, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Power',
                'verbose_name_plural': 'Powers',
                'db_table': 'power',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='hero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='hero',
            name='is_active',
            field=models.BooleanField(db_column='cs_active', default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='hero',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_column='dt_modified', null=True, verbose_name='Modified at'),
        ),
        migrations.AddField(
            model_name='hero',
            name='power',
            field=models.ForeignKey(db_column='id_power', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='powers', to='core.power', verbose_name='Power'),
        ),
    ]
